---
- hosts: all
  gather_facts: no
  tasks:
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Add ansible user to docker group
    user:
      name: ansible
      group: docker

  handlers:
  - name: docker status
    service:
      name: docker
      state: started

  - name: GIT clone
    git:
      repo: git://github.com/marley-nodejs/cats-app
      dest: /home/ansible/cats-app
      clone: yes
      force: yes

  - name: build the image
    docker_image: >
      name=cats-app-docker-image
      tag=latest
      path=/home/ansible/cats-app
      state=present

  - name: run the site in a docker container
    docker:
      name: cats-app-docker-container
      image: "cats-app-docker-image:latest"
      state: reloaded
      publish_all_ports: yes