---
- hosts: all
  gather_facts: no
  tasks:
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
#      - containerd.io
    notify:
      - docker status

  - name: Add ansible user to docker group
    user:
      name: ansible
      group: docker

  # - name: Install dependencies
  #   apt:
  #     name:
  #       - python3-pip
  #     state: latest
  #     update_cache: True
  # - name: Install required pip packages
  #   pip:
  #     name:
  #       - docker-py
  #     executable: pip3

  - name: Install pip
    apt: name=python-pip state=present
  - name: install docker-py package
    pip: name=docker-py

  - name: GIT clone
    git:
      repo: git://github.com/marley-nodejs/cats-app
      dest: /home/ansible/cats-app
      clone: yes
#      force: yes

  # - name: build the image
  #   docker_image: >
  #     name=cats-app-docker-image
  #     tag=latest
  #     build.path=/home/ansible/cats-app/Dockerfile
  #     state=present

  # - name: run the site in a docker container
  #   docker:
  #     name: cats-app-docker-container
  #     image: "cats-app-docker-image:latest"
  #     state: reloaded
  #     publish_all_ports: yes

  - name: Build Docker image from Dockerfile
    docker_image:
      name: cats-app-docker-image
      build.path: /home/ansible/cats-app/Dockerfile
      state: build
      
  - name: Running the container
    docker_container:
      name: cats-app-docker-container
      image: cats-app-docker-image:latest
      path: docker
      publish_all_ports: yes
      state: reloaded

  handlers:
  - name: docker status
    service:
      name: docker
      state: started