---
- hosts: all
  gather_facts: no
  tasks:
    - name: Installing nodejs and git
      become: yes
      apt:
        name: ["npm", "git"]
        state: latest

    - name: GIT clone
      git:
        repo: git://github.com/marley-nodejs/cats-app
        dest: /home/ansible/cats-app
        clone: yes
        force: yes

    - name: Cats app installation
      npm:
        path: /home/ansible/cats-app

    - name: Forever installation
      become: yes
      npm:
        name: forever
        global: true
        state: present

    - name: Run cats app as daemon
      command: forever start --minUptime 1000 --spinSleepTime 1000 /home/ansible/cats-app/index.js
#     register: something

    - name: Install and run Nginx
      package:
        name: nginx
        state: latest

    - name: copy the nginx config file
      copy:
        src: ./nginx/nginx.conf
        dest: /etc/nginx/sites-enabled/default

    - name: start nginx
      service:
        name: nginx
        enabled: true
        state: restarted

    - name: test that webserver is available
      uri:
        url: http://192.168.0.12
        status_code: 200
