---
- hosts: all
  gather_facts: no
  tasks:
  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install docker and its dependecies
      apt: 
        pkg: ['docker-ce', 'docker-ce-cli']
        state: present
        update_cache: true

  - name: Add ansible user to docker group
    user:
      name: ansible
      group: docker

  - name: Install pip3
      apt: 
        pkg: ['python3-pip']
        state: present

  - name: install docker-py package
    pip: name=docker-py

  - name: GIT clone Cats App
    git:
      repo: git://github.com/marley-nodejs/cats-app
      dest: /home/ansible/cats-app
      clone: yes

  - name: Build Docker image from Dockerfile
    docker_image:
      name: cats-app-docker-image
      path: /home/ansible/cats-app
      state: present
      
  - name: Running the container
    docker_container:
      name: cats-app-docker-container
      image: cats-app-docker-image:latest
      state: started
      ports:
        - "8080:8080"

  - name: Install and run Nginx
    package:
      name: nginx
      state: latest

  - name: GIT clone Nginx Script
    git:
      repo: git://github.com/marley-nodejs/cats-app-ansible
      dest: /home/ansible/cats-app-ansible
      clone: yes

  - name: copy the nginx config file
    copy:
      src: /home/ansible/cats-app-ansible/nginx/nginx.conf
      dest: /etc/nginx/sites-enabled/default

  - name: start nginx
    service:
      name: nginx
      enabled: true
      state: restarted

  - name: test that webserver is available
    uri:
      url: http://192.168.0.12
      status_code: 200

    # handlers:
    # - name: docker status
    #   service:
    #     name: docker
    #     state: started